### ISSUE TITLE
Version 1 Roadmap

### ISSUE THREAD

**Issue by keyflight** [entercosmos/attachment-field#1]
## General

- [ ] Support audio controls
- [ ] Support video controls
- [ ] Open slideshow when clicking attachments
- [ ] Show loading indicator when loading attachments

### Editor role
- [ ] Support reordering attachments
- [ ] Support renaming attachments
- [ ] Support removing attachments
- [ ] Support dragndrop
